config/routes.rb
HangzhouPublicBicycleServer::Application.routes.draw do
  resources :stations do
  	collection do
		get 'search'
	end
  end

end

app/models/hzbus.com.rb
# encoding: utf-8
require 'open-uri'
require 'hpricot'

module Hzbus
	def Hzbus.search(latitude, longitude, radius = 1000)
		stations = []
		base_url = "http://www.hzbus.cn/bg.axd?"
		url = "#{base_url}c=1007&w=#{radius}&h=#{radius}&x=#{radius}"
		open(url) { |f|
			Hpricot(f).search("row").each do |row|
				station = Hash.new
				station['name'] = row['fname']
				station['address'] = row['faddress']
				station['latitude'] = row['fshape'].split[0].to_f
				station['longitude'] = row['fshape'].split[1].to_f
				station['space'] = row['fcount'].to_i
				station['idle'] = row['femptycount'].to_i
				station['openTime'] = row['fservicetime'].split('-')[0].split(':')[0].to_i
				station['closeTime'] = row['fservicetime'].split('-')[1].split(':')[0].to_i
				station['localId'] = row['fid']
				station['functioning'] = row['fsummany'].eql?("正常营运中")
				stations << station
				puts station
			end
		}
	end
end

app/models/station.rb
# encoding: utf-8
require 'open-uri'
require 'hpricot'

class Station < ActiveRecord::Base

	def self.search(latitude, longitude, radius = 1000)
		arr = self.fetch(latitude, longitude, radius)
		arr.each do |s|
			station = Station.find_by_localId(s['localId'])
			if (station.nil?)
				station = Station.new(s)
				station.save
			else
				station.attributes = s
				station.save
			end
		end
		arr.length
	end

private
	def self.fetch(latitude, longitude, radius = 1000)
		stations = []
		base_url = "http://www.hzbus.cn/bg.axd?"
		url = "#{base_url}c=1007&w=#{radius}&h=#{radius}&x=#{latitude}&y=#{longitude}"
		open(url) { |f|
			Hpricot(f).search("row").each do |row|
				station = Hash.new
				station['name'] = row['fname'].to_s
				station['address'] = row['faddress'].to_s
				station['latitude'] = row['fshape'].split[0].to_f
				station['longitude'] = row['fshape'].split[1].to_f
				station['space'] = row['fcount'].to_i
				station['idle'] = row['femptycount'].to_i
				station['openTime'] = row['fservicetime'].split('-')[0].split(':')[0].to_i
				station['closeTime'] = row['fservicetime'].split('-')[1].split(':')[0].to_i
				station['localId'] = row['fid'].to_s
				station['functioning'] = row['fsummary'].to_s.eql?("正常营运中")
				stations << station
			end
		}
		stations
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations/search
  # GET /stations/search.json
  def search
	if (params[:latitude] && params[:longitude])
	  Station.search(params[:latitude], params[:longitude])
	end
    @stations = Station.all

    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @stations }
    end
  end

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @station = Station.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.json
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(params[:station])

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render json: @station, status: :created, location: @station }
      else
        format.html { render action: "new" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stations/1
  # PUT /stations/1.json
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HangzhouPublicBicycleServer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :space %><br />
    <%= f.number_field :space %>
  </div>
  <div class="field">
    <%= f.label :idle %><br />
    <%= f.number_field :idle %>
  </div>
  <div class="field">
    <%= f.label :openTime %><br />
    <%= f.number_field :openTime %>
  </div>
  <div class="field">
    <%= f.label :closeTime %><br />
    <%= f.number_field :closeTime %>
  </div>
  <div class="field">
    <%= f.label :cityId %><br />
    <%= f.number_field :cityId %>
  </div>
  <div class="field">
    <%= f.label :localId %><br />
    <%= f.text_field :localId %>
  </div>
  <div class="field">
    <%= f.label :manual %><br />
    <%= f.check_box :manual %>
  </div>
  <div class="field">
    <%= f.label :functioning %><br />
    <%= f.check_box :functioning %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Space</th>
    <th>Idle</th>
    <th>Opentime</th>
    <th>Closetime</th>
    <th>Cityid</th>
    <th>Localid</th>
    <th>Manual</th>
    <th>Functioning</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.name %></td>
    <td><%= station.address %></td>
    <td><%= station.latitude %></td>
    <td><%= station.longitude %></td>
    <td><%= station.space %></td>
    <td><%= station.idle %></td>
    <td><%= station.openTime %></td>
    <td><%= station.closeTime %></td>
    <td><%= station.cityId %></td>
    <td><%= station.localId %></td>
    <td><%= station.manual %></td>
    <td><%= station.functioning %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/search.html.erb
<h1>Listing stations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Space</th>
    <th>Idle</th>
    <th>Opentime</th>
    <th>Closetime</th>
    <th>Cityid</th>
    <th>Localid</th>
    <th>Manual</th>
    <th>Functioning</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.name %></td>
    <td><%= station.address %></td>
    <td><%= station.latitude %></td>
    <td><%= station.longitude %></td>
    <td><%= station.space %></td>
    <td><%= station.idle %></td>
    <td><%= station.openTime %></td>
    <td><%= station.closeTime %></td>
    <td><%= station.cityId %></td>
    <td><%= station.localId %></td>
    <td><%= station.manual %></td>
    <td><%= station.functioning %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @station.name %>
</p>

<p>
  <b>Address:</b>
  <%= @station.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @station.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @station.longitude %>
</p>

<p>
  <b>Space:</b>
  <%= @station.space %>
</p>

<p>
  <b>Idle:</b>
  <%= @station.idle %>
</p>

<p>
  <b>Opentime:</b>
  <%= @station.openTime %>
</p>

<p>
  <b>Closetime:</b>
  <%= @station.closeTime %>
</p>

<p>
  <b>Cityid:</b>
  <%= @station.cityId %>
</p>

<p>
  <b>Localid:</b>
  <%= @station.localId %>
</p>

<p>
  <b>Manual:</b>
  <%= @station.manual %>
</p>

<p>
  <b>Functioning:</b>
  <%= @station.functioning %>
</p>


<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>